<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Login_callout</name>
   <tag></tag>
   <elementGuidId>35dcaea3-7c75-4c65-b13e-e3ecbdf84dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='callout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7735b99a-a0c0-4864-80bb-632a1a6cc355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8ae68ddd-a546-44d0-9ef4-99d61489a698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>08c557dd-bd57-4e47-b652-07c6fbf7c292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>96c1fb83-0171-4920-9287-79228999189b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callout</value>
      <webElementGuid>4e46bfb9-32aa-410e-b8a3-808f4e75bdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ogs.google.co.id/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=b4293de2ee442ece&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Fwww.google.co.id&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=id</value>
      <webElementGuid>e0637900-453c-46cb-8c69-ddc052189b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c45061c3-b664-4394-a6d9-bb48a2145c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75d9db41-e521-4210-b378-842d23f1c653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Bd gb_eb gb_qd&quot;]/div[3]/iframe[1]</value>
      <webElementGuid>514d3c9b-68a1-478e-83f7-33f815c8be3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='callout']</value>
      <webElementGuid>aff594af-8735-4b6d-b926-e0f4ba039f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[3]/iframe</value>
      <webElementGuid>9c714c48-ece8-4c8d-8a31-a58b1ae99de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>99ca5edf-b2a4-4d22-bf94-ff42ae8a7803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.co.id/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=b4293de2ee442ece&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Fwww.google.co.id&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=id']</value>
      <webElementGuid>0528a343-1517-46a2-bcf3-5a1446aca95f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
