<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FacebookMeta</name>
   <tag></tag>
   <elementGuidId>fbce9d9f-b5b4-4dfb-9d8b-5a6e72ca4619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jZ2SBf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jZ2SBf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;facebook&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18a28b45-8537-4c76-8237-190160d72118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnnVSe</value>
      <webElementGuid>f0c02f5a-caa1-43e8-9557-0e16ef73ffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8f81d51-853e-4cf9-9c7d-2db0d9d8d11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d73b8c54-44fa-4b97-9280-429630598185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jZ2SBf</value>
      <webElementGuid>9b64850c-9ec7-4481-829e-0e08a9f0b412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>facebook</value>
      <webElementGuid>043cdaf3-c1b2-434f-85eb-c5b4daa93b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-description</name>
      <type>Main</type>
      <value>Meta</value>
      <webElementGuid>a75e6f9a-ea89-4c28-97d0-c18a808ab357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FacebookMeta</value>
      <webElementGuid>d98bce33-6c51-450b-aced-8f316deb8ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jZ2SBf&quot;)</value>
      <webElementGuid>f32d532b-14a4-4d2c-bb1e-59838bb2393a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='jZ2SBf']</value>
      <webElementGuid>b7efe6fd-7f0a-48ab-9bb5-a92805751f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Alh6id']/div/div/ul/li/div/div[2]/div</value>
      <webElementGuid>b79e0ec5-07cb-4aeb-9a43-a4c5b1f84dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih elemen yang akan diberi masukan'])[1]/following::div[13]</value>
      <webElementGuid>69dbd48e-7cf1-4726-a8da-4875ef5f9330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[47]</value>
      <webElementGuid>be4516c1-2845-4211-a30d-26ac0dd34786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/div</value>
      <webElementGuid>d84f1903-ea54-4ad4-8c7f-2e7a7bb4ff4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'jZ2SBf' and (text() = 'FacebookMeta' or . = 'FacebookMeta')]</value>
      <webElementGuid>9bc81a55-79f4-4897-9e80-9bd2182b18a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
